auth:
  providers:
    awsalb:
      issuer: 'https://backstage-auth-feedutopia.auth.us-east-2.amazoncognito.com'
      signer: 'arn:aws:elasticloadbalancing:us-east-2:825765422855:loadbalancer/app/backstage-alb/1a85036fb16efdde'
      region: 'us-east-2'
      signIn:
        resolvers:
          - resolver: emailMatchingUserEntityProfileEmail

techdocs:
  builder: 'external'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: 'backstage-techdocs-feedutopia'

backend:
  # The baseUrl should be the externally accessible URL to the backend.
  baseUrl: https://backstage.feedutopia.com
  # Binding on all interfaces. Adjust to your environment if needed.
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

catalog:
  # Replace or remove these example catalog locations for your production setup.
  locations:
    - type: file
      target: ./examples/entities.yaml

    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
